<?php

namespace Gestion\BibliothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmprunterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmprunterRepository extends EntityRepository
{
    public function FindByEmprunteur($lecteur)
    {
        /*$query = $this->getEntityManager()
                    ->createQuery('SELECT e FROM GestionBibliothequeBundle:Emprunter e
                                            WHERE e.lecteur.nomLecteur = "'.$nomLecteur.'"');*/
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder->where('e.emprunteur = :lecteur')
                    ->setParameter('lecteur',$lecteur);
        return $queryBuilder->getQuery()->getResult();
    }
//----------------------------------------------------------------------------------------------
    public function FindByExemplaire($exemplaire)
    {
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder->where('e.exemplaire = :exemplaire')
            ->setParameter('exemplaire',$exemplaire);
        return $queryBuilder->getQuery()->getResult();
    }
  //----------------------------------------------------------------------------------------------
    public function FindHorsDelais(){
        $date = new \DateTime();
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder->where('e.dateFin < :date')
            ->setParameter('date',$date);
        return $queryBuilder->getQuery()->getResult();

    }
}
