<?php

namespace Gestion\BibliothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtagereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtagereRepository extends EntityRepository
{
}
