<?php

namespace Gestion\BibliothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExemplaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExemplaireRepository extends EntityRepository
{

    public function FindByLivre($id, $nombreDispo)
    {
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder->join('e.livre','l','WITH','l.id = :id')
                    ->leftJoin('e.emprunter','emp')
                    ->where('emp.exemplaire IS NULL')
                    ->setMaxResults($nombreDispo)
                    ->setParameter('id',$id);
        return $queryBuilder;
    }
}
