<?php

namespace Gestion\BibliothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecteurRepository extends EntityRepository
{
    public function FindByName($nom)
    {
        $queryBuilder = $this->createQueryBuilder('l');
        $queryBuilder->where('l.nomLecteur = :nom')
            ->setParameter('nom',$nom);
        return $queryBuilder->getQuery()->getResult();
    }
}
