Gestion\BibliothequeBundle\Entity\Rayon:
    type: entity
    table: null
    repositoryClass: Gestion\BibliothequeBundle\Entity\RayonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        designationRayon:
            type: string
            length: '20'
            column: designation_rayon
    oneToMany:
        etageres:
            targetEntity: Etagere
            mappedBy: rayon
            orphanRemoval: true
    manyToOne:
        theme_rayon:
            targetEntity: Theme
            inversedBy: rayon
            cascade : [ persist ]

